# Generated by Django 4.0.4 on 2022-06-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100, verbose_name='categorie')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('recoil_x', models.CharField(max_length=100, verbose_name='recoil_x')),
                ('recoil_y', models.CharField(max_length=100, verbose_name='recoil_y')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bushka_site/img', verbose_name='image')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='bushka_site.categorie', verbose_name='autorius')),
            ],
        ),
    ]
